# Generated by Django 5.2.11 on 2026-02-28 08:55

import apps.appointments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('lock_type', models.CharField(choices=[('PIN', 'PIN'), ('GOOGLE', 'GOOGLE'), ('APPLE_ID', 'APPLE_ID'), ('OTHER', 'OTHER')], max_length=20)),
                ('has_pc', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('photo_lock_screen', models.FileField(blank=True, null=True, upload_to='lock_screen/', validators=[apps.appointments.models.validate_image_file])),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_REVIEW', 'В работе мастера'), ('AWAITING_PAYMENT', 'Ожидает оплату'), ('PAYMENT_PROOF_UPLOADED', 'Чек загружен'), ('PAID', 'Оплачено'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('DECLINED_BY_MASTER', 'Отклонено мастером'), ('CANCELLED', 'Отменено')], db_index=True, default='NEW', max_length=40)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('bank_transfer', 'Bank transfer')], max_length=20, null=True)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/', validators=[apps.appointments.models.validate_payment_proof])),
                ('payment_marked_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status changed'), ('price_set', 'Price set'), ('payment_proof_uploaded', 'Payment proof uploaded'), ('payment_marked', 'Payment marked'), ('payment_confirmed', 'Payment confirmed'), ('message_deleted', 'Message deleted')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appointments.appointment')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
