# Generated by Django 5.2.11 on 2026-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='platform_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
