# Generated by Django 5.2.11 on 2026-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_platform_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completion_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='response_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sla_breached',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
