# Generated by Django 5.2.11 on 2026-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_completion_deadline_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentevent',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status changed'), ('price_set', 'Price set'), ('payment_proof_uploaded', 'Payment proof uploaded'), ('payment_marked', 'Payment marked'), ('payment_confirmed', 'Payment confirmed'), ('message_deleted', 'Message deleted'), ('client_signal', 'Client signal')], max_length=40),
        ),
    ]
