# Generated by Django 5.2.11 on 2026-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointmentevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="rustdesk_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rustdesk_password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
