# Generated by Django 5.2.11 on 2026-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointment_rustdesk_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
