# Generated by Django 5.2.11 on 2026-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appointment_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_wholesale_request",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="wholesale_base_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="wholesale_discount_percent_applied",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
