# Generated by Django 5.2.11 on 2026-03-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_appointment_is_wholesale_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_requisites_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
