# Generated by Django 5.2.11 on 2026-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_appointment_payment_requisites_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="lock_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "GOOGLE"),
                    ("HUAWEI_ID", "HUAWEI_ID"),
                    ("MI_ACC", "MI_ACC"),
                    ("APPLE_ID", "APPLE_ID"),
                    ("OTHER", "OTHER"),
                    ("PIN", "PIN"),
                ],
                max_length=20,
            ),
        ),
    ]
