# Generated by Django 5.2.11 on 2026-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('trigger_event_type', models.CharField(db_index=True, max_length=120)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('action_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'trigger_event_type'], name='platform_ru_is_acti_b0cec1_idx')],
            },
        ),
    ]
