# Generated by Django 5.2.11 on 2026-03-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('gmv_total', models.BigIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_appointments', models.PositiveIntegerField(default=0)),
                ('paid_appointments', models.PositiveIntegerField(default=0)),
                ('completed_appointments', models.PositiveIntegerField(default=0)),
                ('avg_time_to_first_response', models.FloatField(default=0.0)),
                ('avg_time_to_complete', models.FloatField(default=0.0)),
                ('conversion_new_to_paid', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
