# Generated by Codex on 2026-03-01

from django.db import migrations


def seed_sla_breach_rule(apps, schema_editor):
    Rule = apps.get_model("platform", "Rule")
    Rule.objects.get_or_create(
        name="default_sla_breach_admin_attention",
        defaults={
            "is_active": True,
            "trigger_event_type": "sla.breached",
            "condition_json": {},
            "action_json": {
                "type": "request_admin_attention",
                "title": "SLA нарушен",
                "message": "Обнаружено нарушение SLA по заявке",
            },
        },
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0003_dailymetrics"),
    ]

    operations = [
        migrations.RunPython(seed_sla_breach_rule, noop_reverse),
    ]
