server {
    listen 80;
    listen [::]:80;
    server_name admin.frpclient.ru;

    client_max_body_size 25m;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
