from django.urls import path

from .views import (
    AuthLogoutView,
    BootstrapCreateAdminView,
    BootstrapStatusView,
    CookieTokenObtainPairView,
    CookieTokenRefreshView,
    ClientProfileDetailView,
    DashboardSummaryView,
    EmailVerifyView,
    MeView,
    MeProfileUpdateView,
    OAuthCallbackView,
    OAuthStartView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    RegisterResendVerificationView,
    TelegramAuthView,
    WholesalePortalOrdersView,
    WholesalePortalProfileView,
    WholesalePortalSummaryView,
    WholesaleRequestView,
    WholesaleStatusView,
)

urlpatterns = [
    path("auth/bootstrap-status/", BootstrapStatusView.as_view(), name="auth-bootstrap-status"),
    path("auth/bootstrap-admin/", BootstrapCreateAdminView.as_view(), name="auth-bootstrap-admin"),
    path("auth/login/", CookieTokenObtainPairView.as_view(), name="auth-login"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/register/resend-verification/", RegisterResendVerificationView.as_view(), name="auth-register-resend-verification"),
    path("auth/verify-email/", EmailVerifyView.as_view(), name="auth-verify-email"),
    path("auth/password-reset/", PasswordResetRequestView.as_view(), name="auth-password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="auth-password-reset-confirm"),
    path("auth/telegram/", TelegramAuthView.as_view(), name="auth-telegram"),
    path("auth/oauth/<str:provider>/start/", OAuthStartView.as_view(), name="auth-oauth-start"),
    path("auth/oauth/<str:provider>/callback/", OAuthCallbackView.as_view(), name="auth-oauth-callback"),
    path("auth/logout/", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/refresh/", CookieTokenRefreshView.as_view(), name="auth-refresh"),
    path("me/", MeView.as_view(), name="me"),
    path("me/profile/", MeProfileUpdateView.as_view(), name="me-profile-update"),
    path("clients/<int:user_id>/profile/", ClientProfileDetailView.as_view(), name="client-profile-detail"),
    path("wholesale/status/", WholesaleStatusView.as_view(), name="wholesale-status"),
    path("wholesale/request/", WholesaleRequestView.as_view(), name="wholesale-request"),
    path("wholesale/portal/summary/", WholesalePortalSummaryView.as_view(), name="wholesale-portal-summary"),
    path("wholesale/portal/orders/", WholesalePortalOrdersView.as_view(), name="wholesale-portal-orders"),
    path("wholesale/portal/profile/", WholesalePortalProfileView.as_view(), name="wholesale-portal-profile"),
    path("dashboard/", DashboardSummaryView.as_view(), name="dashboard-summary"),
]
