# Generated by Django 5.2.11 on 2026-03-01 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientstats_risk_level_clientstats_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('avg_response_seconds', models.FloatField(default=0.0)),
                ('active_workload', models.PositiveIntegerField(default=0)),
                ('cancellation_rate', models.FloatField(default=0.0)),
                ('master_score', models.PositiveSmallIntegerField(default=0)),
                ('score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
