# Generated by Django 5.2.11 on 2026-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_masterstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sla_completion_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sla_response_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
