# Generated by Django 5.2.11 on 2026-03-02 11:10

from django.db import migrations, models
from django.utils import timezone


def approve_existing_active_masters(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    now = timezone.now()
    User.objects.filter(role="master", is_master_active=True).update(
        master_quality_approved=True,
        master_quality_approved_at=now,
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sitesettings_sla_completion_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="master_level",
            field=models.CharField(
                choices=[
                    ("trainee", "Стажер"),
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                ],
                default="junior",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="master_quality_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="master_quality_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="master_quality_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="master_specializations",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(approve_existing_active_masters, noop_reverse),
    ]
