# Generated by Django 5.2.11 on 2026-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_master_quality_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_service_center",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_comment",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_discount_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_review_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_status",
            field=models.CharField(
                choices=[
                    ("none", "Не запрошено"),
                    ("pending", "На рассмотрении"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                db_index=True,
                default="none",
                max_length=20,
            ),
        ),
    ]
