# Generated by Django 5.2.11 on 2026-03-03 12:00

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_service_center_user_wholesale_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wholesale_service_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_service_photo_1",
            field=models.FileField(blank=True, null=True, upload_to="service_centers/", validators=[apps.accounts.models.validate_service_photo]),
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_service_photo_2",
            field=models.FileField(blank=True, null=True, upload_to="service_centers/", validators=[apps.accounts.models.validate_service_photo]),
        ),
    ]
