# Generated by Django 5.2.11 on 2026-03-03 13:20

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_wholesale_service_details_and_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                validators=[apps.accounts.models.validate_profile_photo],
            ),
        ),
    ]
