# Generated by Django 5.2.11 on 2026-03-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_wholesale_verified_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=96, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="accounts_pa_user_id_c7800e_idx"),
                    models.Index(fields=["expires_at"], name="accounts_pa_expires_101598_idx"),
                ],
            },
        ),
    ]
