from django.urls import path

from .views import (
    AdminActivateMasterView,
    AdminAllUsersView,
    AdminAppointmentListView,
    AdminBanUserView,
    AdminClientsView,
    AdminConfirmPaymentView,
    AdminDeleteAppointmentView,
    AdminFinanceSummaryView,
    AdminMastersView,
    AdminMasterQualityUpdateView,
    AdminPaymentRegistryExportCsvView,
    AdminPaymentRegistryView,
    WeeklyPerformanceReportView,
    AdminWholesalePriorityView,
    AdminWholesaleRequestsView,
    AdminWholesaleReviewView,
    AdminSystemRunActionView,
    AdminSystemSettingsView,
    AdminSystemStatusView,
    AdminSuspendMasterView,
    AdminUnbanUserView,
    AdminUserRoleUpdateView,
)

urlpatterns = [
    path("admin/appointments/", AdminAppointmentListView.as_view(), name="admin-appointments-list"),
    path("admin/appointments/<int:appointment_id>/confirm-payment/", AdminConfirmPaymentView.as_view(), name="admin-appointments-confirm-payment-2"),
    path("admin/appointments/<int:appointment_id>/", AdminDeleteAppointmentView.as_view(), name="admin-appointments-delete"),
    path("admin/finance/summary/", AdminFinanceSummaryView.as_view(), name="admin-finance-summary"),
    path("admin/payments/registry/", AdminPaymentRegistryView.as_view(), name="admin-payments-registry"),
    path("admin/payments/registry/export/", AdminPaymentRegistryExportCsvView.as_view(), name="admin-payments-registry-export"),
    path("admin/reports/weekly/", WeeklyPerformanceReportView.as_view(), name="admin-reports-weekly"),
    path("admin/users/", AdminClientsView.as_view(), name="admin-users-list"),
    path("admin/wholesale-requests/", AdminWholesaleRequestsView.as_view(), name="admin-wholesale-requests"),
    path("admin/wholesale-requests/<int:user_id>/review/", AdminWholesaleReviewView.as_view(), name="admin-wholesale-review"),
    path("admin/users/<int:user_id>/wholesale-priority/", AdminWholesalePriorityView.as_view(), name="admin-wholesale-priority"),
    path("admin/users/all/", AdminAllUsersView.as_view(), name="admin-users-all"),
    path("admin/users/<int:user_id>/ban/", AdminBanUserView.as_view(), name="admin-users-ban"),
    path("admin/users/<int:user_id>/unban/", AdminUnbanUserView.as_view(), name="admin-users-unban"),
    path("admin/users/<int:user_id>/role/", AdminUserRoleUpdateView.as_view(), name="admin-users-role"),
    path("admin/masters/", AdminMastersView.as_view(), name="admin-masters-list"),
    path("admin/masters/<int:user_id>/activate/", AdminActivateMasterView.as_view(), name="admin-masters-activate"),
    path("admin/masters/<int:user_id>/suspend/", AdminSuspendMasterView.as_view(), name="admin-masters-suspend"),
    path("admin/masters/<int:user_id>/quality/", AdminMasterQualityUpdateView.as_view(), name="admin-masters-quality-update"),
    path("admin/system/status/", AdminSystemStatusView.as_view(), name="admin-system-status"),
    path("admin/system/settings/", AdminSystemSettingsView.as_view(), name="admin-system-settings"),
    path("admin/system/run-action/", AdminSystemRunActionView.as_view(), name="admin-system-run-action"),
]
