# Generated by Django 5.2.11 on 2026-02-28 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('bad_internet', 'Проблемный интернет'), ('weak_pc', 'Слабый ПК'), ('difficult_client', 'Сложный клиент'), ('did_not_follow_instructions', 'Не следовал инструкциям'), ('late_to_session', 'Опоздал к подключению'), ('good_connection', 'Отличная связь'), ('well_prepared', 'Подготовлен заранее')], max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('master_review', 'Client -> Master'), ('client_review', 'Master -> Client')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appointments.appointment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_reviews', to=settings.AUTH_USER_MODEL)),
                ('behavior_flags', models.ManyToManyField(blank=True, related_name='reviews', to='reviews.behaviorflag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(fields=('appointment', 'review_type'), name='uniq_review_type_per_appointment')],
            },
        ),
    ]
