# Generated by Django 5.2.11 on 2026-03-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_masterquickreply'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='masterquickreply',
            new_name='chat_master_user_id_44eb1d_idx',
            old_name='chat_mqr_user_cmd_idx',
        ),
    ]
