# Generated by Django 5.2.11 on 2026-03-03 01:26

import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_chat_mqr_user_cmd_idx_chat_master_user_id_44eb1d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterquickreply',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='quick_reply_media/', validators=[apps.chat.models.validate_quick_reply_media]),
        ),
        migrations.AlterField(
            model_name='masterquickreply',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
